# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


		default_items = DefaultItem.create(
				[{ item: 'Toothpaste'},
					{item: 'Dental Floss'},
					{item: 'Soap'},
					{item: 'Deodorant'},
					{item: 'Shampoo'},
					{item: 'Brush'},
					{item: 'Hairstyling Essentials'},
					{item: 'Face Cleanser'},
					{item: 'Face Lotion'},
					{item: 'Sunscreen'},
					{item: 'Moisturizer'},
					{item: 'Contact Lenses'},
					{item: 'Shaving Supplies'},
					{item: 'Makeup'},
					{item: 'Makeup Remover'},
					{item: 'Hygeine Products'},
					{item: 'Nail file / Clippers'},
					{item: 'Tweezers'},
					{item: 'Hand Sanitizer'},
					{item: 'Bandages'},
					{item: 'First Aid Kit'},
					{item: 'Insect Repellant'},
					{item: 'Medications'},
					{item: 'Pain Relievers'},
					{item: 'Vitamins'},
					{item: 'Laundry Kit'},
					{item: 'Laundry Bag'},
					{item: 'Leisure Shoes'},
					{item: 'Underwear'},
					{item: 'Socks'},
					{item: 'Sleepwear'},
					{item: 'T-Shirts'},
					{item: 'Dress Shirts'},
					{item: 'Casual Shirts'},
					{item: 'Jeans'},
					{item: 'Pants'},
					{item: 'Shorts'},
					{item: 'Dresses'},
					{item: 'Skirts'},
					{item: 'Sweaters'},
					{item: 'Coats / Jackets'},
					{item: 'Hats'},
					{item: 'Gloves'},
					{item: 'Scarves'},
					{item: 'Umbrella'},
					{item: 'Athletic Shoes'},
					{item: 'Rain Boots'},
					{item: 'Dress Shoes'},
					{item: 'Sandals / Flip-Flops'},
					{item: 'Belts'},
					{item: 'Ties'},
					{item: 'Jewelry'},
					{item: 'Purses'},
					{item: 'Collapsible Totes'},
					{item: 'Plain Tickets'},
					{item: 'Hotel Confirmation'},
					{item: 'Rental Car Confirmation'},
					{item: 'Cash / Credit Cards'},
					{item: 'Dollar Bills for Tips'},
					{item: 'Checkbook'},
					{item: 'Passports'},
					{item: 'Birth Certificates'},	
					{item: 'ID / Drivers License'},
					{item: 'Health Insurance Card'},
					{item: 'Maps / Directions'},
					{item: 'Membership Cards'},
					{item: 'Address Book'},
					{item: 'Notepad / Pens'},
					{item: 'Batteries'},
					{item: 'Cameras / Chargers'},
					{item: 'Camera Lenses'},
					{item: 'Camera Tripod'},
					{item: 'Cellphones / Chargers'},
					{item: 'MP3 Player'},
					{item: 'Laptops / Chargers'},
					{item: 'Headphones'},
					{item: 'Multipower Outlet'},
					{item: 'Voltage Adaptor'},
					{item: 'Hair Dryer'},
					{item: 'Watch'},
					{item: 'Alarm Clock'},
					{item: 'GPS'},
					{item: 'Books'},
					{item: 'Tissues'},
					{item: 'Travel Pillow'},
					{item: 'Lip Balm'},
					{item: 'Change of Clothes'},
					{item: 'Empty Water Bottle'},
					{item: 'In-flight Medications'},
					{item: 'Valuables'},
					{item: 'Sleeping Mask'},
					{item: 'Multi-tool'},
					{item: 'Bottle Opener'},	
					{item: 'Cork Screw'},
					{item: 'Poker Cards'},
					{item: 'Lighter'},
					{item: 'Flash Light'},
					{item: 'Sunglasses'},
					{item: 'Safety Pins'},
					{item: 'Duct Tape'},
					{item: 'Super Glue'}])